import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="flex h-screen">
      <aside className="w-64 bg-gray-900 text-white p-4">
        <h2 className="text-2xl font-bold mb-4">Dashboard</h2>
        <nav>
          <ul>
            <li className="mb-2">
              <a href="/" className="block py-2 px-4 rounded hover:bg-gray-700">
                Home
              </a>
            </li>
            <li className="mb-2">
              <a href="/profile" className="block py-2 px-4 rounded hover:bg-gray-700">
                Profile
              </a>
            </li>
            <li className="mb-2">
              <a href="/settings" className="block py-2 px-4 rounded hover:bg-gray-700">
                Settings
              </a>
            </li>
            <li className="mb-2">
              <a
                href="/users"
                className="block py-2 px-4 rounded hover:bg-gray-700"
              >
                Users
              </a>
            </li>
          </ul>
        </nav>
      </aside>
      <main className="flex-1 p-6 bg-[var(--background)] text-[var(--foreground)]">{children}</main>
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {menuLayout({ children })}
      </body>
    </html>
  );
}
